### ISSUE TITLE
Parallel Test Case execution

### ISSUE THREAD

**Issue by AmarnathN** [anilpandeykiet/POM_HYBRID_FRAMEOWRK#13]
HI Anil,

This is actually a query.

During the  Parallel Execution of Test Cases, As driver is made Static in the Base Class, won't the driver value get affected by the changes in the individual Test cases.

Regards,
Amarnath

**Comment by anilparkin** [comment]
The driver is made static to ensure that the test steps are logged correctly in the respective test case report. 

This is by design.

If there is any specific issue with the same, I would be more than happy to look into it.

**Comment by anilpandeykiet** [comment]
Closing the issue as no response received from the user.
@AmarnathN : Please raise a new issue in case you require more help.
